# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "killercode"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      # Based on https://github.com/marketplace/actions/setup-bazelisk
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel build //...
      - run: tar -tvf bazel-bin/tutorial.tar
      - run: cp bazel-bin/tutorial.tar /tmp/tutorial.tar
      - name: Upload tutorial.tar archive
        uses: actions/upload-artifact@v2
        with:
          retention-days: 1
          name: tutorial-tar
          path: /tmp/tutorial.tar
          if-no-files-found: error
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          repository: git@github.com:TheGrizzlyDev/bazel-for-bears.git
          ref: killercode-release
          clean: true
      - run: rm -rf *
      - run: tar -xf /tmp/tutorial.tar
      - name: Setup git
        run: |
          git config --global user.email "release-bot@why-should-a-bot-have-an-email.com"
          git config --global user.name "release-bot"
      - run: git commit -am "Release from ${{ github.head_ref }}.${{ github.sha }}"
      - run: git push