# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "killercode"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      # Based on https://github.com/marketplace/actions/setup-bazelisk
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel build //...
      - run: tar -tvf bazel-bin/courses/courses.tar
      - run: cp bazel-bin/courses/courses.tar /tmp/courses.tar
      - name: Upload courses.tar archive
        uses: actions/upload-artifact@v2
        with:
          retention-days: 1
          name: tutorial-tar
          path: /tmp/courses.tar
          if-no-files-found: error
  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: killercode-release
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: true
          clean: true
      - run: git rm -rf .
      - uses: actions/download-artifact@v3
        with:
          name: tutorial-tar
      - run: tar -xf courses.tar
      - run: rm courses.tar
      - name: Setup git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - run: git status
      - run: ls -lR
      - run: git add .
      - run: git status
      - run: git commit -m "Release from ${{ github.sha }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          ssh: true
          branch: killercode-release
